### PR TITLE
Fix kwarg handling for Ruby 3.0 compatibility

### PR DESCRIPTION
**Pull request by jasonrudolph**
Prior to this change, the test suite fails on Ruby 3.0.2 as follows seen in https://github.com/jasonrudolph/omniauth-slack/runs/3125654072:

```
   1) Failure:
 ClientTest#test_transfers_team_domain_from_request.params_to_client.site_uri [/home/runner/work/omniauth-slack/omniauth-slack/test/strategy_test.rb:73]:
 Expected: "https://subdomain2.slack.com"
   Actual: "https://slack.com"

   2) Failure:
 ClientTest#test_transfers_history_option_from_strategy_client_options_to_client.history [/home/runner/work/omniauth-slack/omniauth-slack/test/strategy_test.rb:78]:
 Expected: [5]
   Actual: nil

   3) Failure:
 ClientTest#test_transfers_team_domain_from_strategy_options_to_client.site_uri [/home/runner/work/omniauth-slack/omniauth-slack/test/strategy_test.rb:67]:
 Expected: "https://subdomain.slack.com"
   Actual: "https://slack.com"

 60 runs, 99 assertions, 3 failures, 0 errors, 0 skips
```

On Ruby 2.7, running the test suite with deprecation warnings enabled produces the following warnings:

```
$ RUBYOPT='-W:deprecated' bundle exec rake
Mocha deprecation warning at test/helper.rb:16:in `require': Require 'mocha/test_unit', 'mocha/minitest' or 'mocha/api' instead of 'mocha/setup'.
lib/omniauth-slack/oauth2/access_token.rb:127: warning: assigned but unused variable - rslt
Run options: --seed 31711

# Running:

......................lib/omniauth/strategies/slack.rb:187: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
lib/omniauth-slack/oauth2/client.rb:39: warning: The called method `initialize' is defined here
.test/strategy_test.rb:52: warning: method redefined; discarding old request
/Users/j/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/oauth2-1.4.7/lib/oauth2/client.rb:100: warning: previous definition of request was here
.......test/strategy_test.rb:39: warning: method redefined; discarding old request
test/strategy_test.rb:52: warning: previous definition of request was here
.......test/strategy_test.rb:8: warning: method redefined; discarding old auth_hash
/Users/j/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/omniauth-2.0.4/lib/omniauth/strategy.rb:390: warning: previous definition of auth_hash was here
.......................

Finished in 0.043992s, 1363.8843 runs/s, 2250.4092 assertions/s.
```

For the purposes of this pull request, the important warnings to note are these two:

```
lib/omniauth/strategies/slack.rb:187: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
lib/omniauth-slack/oauth2/client.rb:39: warning: The called method `initialize' is defined here
```

This pull request resolves those warnings, which also fixes the test suite on Ruby 3.0 (as seen in https://github.com/jasonrudolph/omniauth-slack/runs/3125709373).

### CODE REVIEW

**Comment by jasonrudolph** [comment]
👋 @ginjo: Do you think this is something you'd consider merging?

If there are any changes you'd like to see, or any questions you have, just let me know, and I'll do my best to follow up. :bow:

**Comment by jasonrudolph** [comment]
👋 @ginjo: Just checking in. It would be awesome to be able to use this gem with Ruby 3.0, and I _think_ this pull request provides everything needed for Ruby 3.0 compatibility. Is there anything I could do that would make this easier to review?

**Comment by kwent** [comment]
+1

**Comment by jasonrudolph** [comment]
👋 @ginjo: Happy New Year! Now that Ruby 3.1 is out, it would be even more awesome to get ginjo/omniauth-slack working with Ruby 3.0. Would you be willing to review this pull request?

**Comment by jasonrudolph** [comment]
I'm closing this pull request so that it no longer shows up on my GitHub dashboard. 😅

@ginjo: Please feel free to re-open it if you'd like to merge it.

**Pull request closed without merging**
